import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import type { ContributionFormInput } from '@/types';

// GET /api/contributions - List contributions for a trust
export async function GET(request: NextRequest) {
  const supabase = await createServerSupabaseClient();

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ data: null, error: 'Unauthorized' }, { status: 401 });
  }

  const trustId = request.nextUrl.searchParams.get('trust_id');

  let query = supabase
    .from('contributions')
    .select(`
      *,
      notices:notices(
        id,
        status,
        recipient_name,
        withdrawal_amount,
        acknowledged_at
      ),
      trust:trusts(id, name)
    `)
    .order('contribution_date', { ascending: false });

  if (trustId) {
    query = query.eq('trust_id', trustId);
  }

  const { data, error } = await query;

  if (error) {
    return NextResponse.json({ data: null, error: error.message }, { status: 500 });
  }

  return NextResponse.json({ data, error: null });
}

// POST /api/contributions - Record a new contribution
export async function POST(request: NextRequest) {
  const supabase = await createServerSupabaseClient();

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ data: null, error: 'Unauthorized' }, { status: 401 });
  }

  const body: ContributionFormInput = await request.json();

  // Validate required fields
  if (!body.trust_id || !body.amount || !body.contribution_date) {
    return NextResponse.json(
      { data: null, error: 'Missing required fields' },
      { status: 400 }
    );
  }

  // Verify user owns this trust
  const { data: trust } = await supabase
    .from('trusts')
    .select('id, name')
    .eq('id', body.trust_id)
    .eq('user_id', user.id)
    .single();

  if (!trust) {
    return NextResponse.json({ data: null, error: 'Trust not found' }, { status: 404 });
  }

  // Check if trust has beneficiaries
  const { count: beneficiaryCount } = await supabase
    .from('beneficiaries')
    .select('*', { count: 'exact', head: true })
    .eq('trust_id', body.trust_id)
    .eq('is_active', true);

  if (!beneficiaryCount || beneficiaryCount === 0) {
    return NextResponse.json(
      { data: null, error: 'Trust has no active beneficiaries. Add beneficiaries before recording contributions.' },
      { status: 400 }
    );
  }

  // Create contribution (notices will be auto-generated by database trigger)
  const { data: contribution, error } = await supabase
    .from('contributions')
    .insert({
      trust_id: body.trust_id,
      amount: body.amount,
      contribution_date: body.contribution_date,
      description: body.description || null,
      is_recurring: body.is_recurring || false,
      recurring_frequency: body.recurring_frequency || 'none',
      recurring_end_date: body.recurring_end_date || null,
    })
    .select(`
      *,
      notices:notices(*)
    `)
    .single();

  if (error) {
    return NextResponse.json({ data: null, error: error.message }, { status: 500 });
  }

  // Log audit event
  await supabase.from('audit_log').insert({
    user_id: user.id,
    action: 'contribution_created',
    entity_type: 'contribution',
    entity_id: contribution.id,
    details: {
      amount: body.amount,
      date: body.contribution_date,
      trust_name: trust.name,
      notices_generated: contribution.notices?.length || 0,
    },
  });

  // If recurring, schedule future contributions
  if (body.is_recurring && body.recurring_frequency && body.recurring_frequency !== 'none') {
    // This would typically be handled by a cron job or edge function
    // For now, we just store the recurring settings
  }

  return NextResponse.json({ data: contribution, error: null });
}
